### ISSUE TITLE
Answering to multiple channels (perhaps over multiple teams)

### ISSUE THREAD

**Issue by devTechi** [renanvicente/hubot-mattermost#7]
Hi,

thanks. Works really fine.

But I got a question. I read the possibility to post to channels if you specify the `channel` in json (see [Incoming-Webhooks](https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Incoming-Webhooks.md#creating-integrations-using-incoming-webhooks) _Additional Notes_, No 2.). How can we do that with hubot?

Isn`t it easier to just response to the POST request of the outgoing webhook like the [giphy script](https://github.com/mattermost/mattermost-integration-giphy). There you don't need to create any incoming webhook. I just realized that because of the script.

Or am I missing something? It would be very cool to have **hubot** answering to all channels.

**Comment by rompic** [comment]
sounds like a great idea (if possible)

**Comment by heitorlessa** [comment]
@devTechi 

Regarding the first question: You can have a single Incoming Hook so that we would have an URL to send POST requests to and then we leverage that with either MATTERMOST_CHANNEL variable OR we use that to post the message back to the channel it came from. 

As regards to the Giphy integration, that's an interesting one Andre! Mainly on "Leave Channel Blank" since last time I tried it didn't work (maybe I did something silly). 

Will give it a spin today as soon as I get my dev environment up and come back to you here with some thoughts on that.

Tks for pointing that out :+1:

**Comment by heitorlessa** [comment]
Hey @devTechi, I've just tested everything out and as I thought it works just fine -- **sending messages to ANY public channel**

There's also a gotcha with that approach since Hubot.hear (_robot.hear /regex$/i_) will stop working. So I've done a couple of more tests and I'm including an extra topic in the documentation (see my next comment). 

Now, concerning not having an Incoming Hook that **will not work** as Hubot needs to forward that into his (robot/TextMessage) in order to Hubot Scripts capture that and call 'send/reply/whatever' method.

In other words, Hubot needs to store that and call built-in methods prior to send that to scripts otherwise it doesn't work properly. That's why we need the Incoming Hook for that so we can send a HTTP POST back to Mattermost once Hubot processes all that. 

On the other hand, another way that could work is to:
- Rewrite Hubot Mattermost adapter to use [Websockets](https://github.com/Rovak/hubot-websocket/blob/master/src/websocket.coffee) instead of Hooks, so that Hubot would appear as a normal user

But I don't see a bandwidth on our side to do this at this stage.

Let me know if you're OK with the new section below and I will update the main page + npm package.

Tks again!

**Comment by heitorlessa** [comment]
New documentation to be updated once you're OK with that:

## Example with Hubot sending to ANY public channel

As pointed out by [Andre](https://github.com/devTechi) there's a [new Giphy implementation](https://github.com/mattermost/mattermost-integration-giphy) that leverages an Outgoing hook with **no channel set**, in which Mattermost allows us to send messages to any channel based on **Trigger Words** feature only.

Therefore, if all you want to do is to have Hubot to send/reply to all public channels, all you will need to do is:
- Create an Outgoing Hook, leave Channel untouched (blank), set the <Hubot Name> (e.g. _matterbot_) as Trigger Word and specify the callback URL as you would normally
- Set _MATTERMOST_TOKEN_ global variable with the token given by the newly Outgoing hook created

Example of a hook created using this pattern:

``` sh
URLs: http://localhost:8080/hubot/incoming
Trigger Words: matterbot
Token: 15r8ybrxhpgifc3rycdjrf6m8e
```

Example of global variables set that will send to **any public channel** if message starts with **matterbot**:

``` sh
export MATTERMOST_ENDPOINT=/hubot/incoming # listen endpoint
export MATTERMOST_INCOME_URL=http://localhost:8065/hooks/3eo1wjwyxibnmd5rsusk4h4pgh # your mattermost income url
export MATTERMOST_TOKEN="epboqd78ufyi58nxktgzq9zpho,7ftco7zg5fdkixw7j3okmuo3eo" # your mattermost token
export MATTERMOST_ICON_URL=https://s3-eu-west-1.amazonaws.com/renanvicente/toy13.png # optional: if you want to override hubot icon
export MATTERMOST_HUBOT_USERNAME="matterbot" # optional: if you want to override hubot name
```

### Known issues

With this approach [**Hubot.hear method**](https://hubot.github.com/docs/scripting/#hearing-and-responding) will be invalidated, since a POST message will only be sent from Mattermost if Hubot name (_MATTERMOST_HUBOT_USERNAME="matterbot"_) is mentioned.

So, if you have the following in any of your custom scripts -- that will **no longer work**:

``` coffeescript
robot.hear /HEY$/i, (msg) ->
    msg.reply "Yo!"
```

#### Workaround

In order to have both working (send messages to any public channel + hubot actively listening to certain messages) you would need to:
- A) Have an Outgoing Hook with **no channel set** with each 'Hear' (e.g 'hey') regex separated by comma
- B) Have an Outgoing Hook to each Channel you want 'Hear' method to work
- Once you define which option you prefer you must update MATTERMOST_TOKEN with the additional token you got (_MATTERMOST_TOKEN="<token1>,<token2>"), otherwise Hubot will simply ignore the incoming event

Example of Outgoing Hook created using option A:

``` sh
URLs: http://localhost:8080/hubot/incoming
Trigger Words: hey
Token: 9r8i6s86hbgc8r57hqc5ywijac
```

By simply typing: _"hey"_ in any channel Hubot should be able to respond with _"Yo!"_ as Mattermost now sends a POST to Hubot.

**Comment by devTechi** [comment]
hi,
thanks for your work. _Well, I didn't get it to work._

What I did:
- I added a new outgoing webhook and left the incoming as it was
- I changed my environment variables and sourced the .bashrc-file
- I replaced the mattermost.coffee file with the new given one

But Hubot keeps answering to the one channel which is specified by the incoming webhook of mattermost. The Trigger word is working fine. If I have multiple outgoing webhooks (with trigger and channel) hubot answers twice (per webhook). But thats no big deal.

Btw. Is it possible the way you described to have hubot answering to multiple teams? Not just channels. With the Giphy implementation that works too. But I understand the reason why we have to have an incoming webhook for the scripts.

thx :smile:

**Comment by heitorlessa** [comment]
It sounds that you have MATTERMOST_CHANNEL variable set (env | grep MATTERMOST_CHANNEL), in which it will only respond back to the channel specified there as opposed to reply via the source channel/team. 
- Would you mind dumping your variables here? feel free to anonymise its data if it's not a dev env

As Mattermost Incoming Hooks don't support 'team' directive Hubot won't be able to send a message across teams but mainly a channel within that team Incoming URL was created. For each team you would need a separated Hubot instance as you would on a Hipchat implementation for instance.

To my understanding, URLs and hooks should be different within teams so the concept of separating threads/conversations would be more valid, but I have to yet review Giphy and Mattermost latest documentation on that.

Either way, it seems to work on Giphy implementation because it simply responds to [Outgoing Hooks](https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Outgoing-Webhooks.md) which [**supports team directive**](https://github.com/mattermost/platform/blob/master/doc/integrations/webhooks/Outgoing-Webhooks.md#creating-integrations-using-outgoing-webhooks).

I'm also happy to join a Mattermost/Slack/IRC to troubleshoot that live with you if you need

UPDATE: It's also important to note that even though your Incoming Hook has a single channel selected, Hubot is able to send/reply a message to another channel as Outgoing Hooks allow that

**Comment by devTechi** [comment]
Well, what should I say :smile: **Now it works!**
You were right. _MATTERMOST_CHANNEL_ variable first had to be unset. My fault. Now my variables look like yours above.

_Environment variables (I changed the values):_

```
export MATTERMOST_ENDPOINT=/hubot/incoming # listen endpoint #http://127.0.0.1:8000/hubot/incoming
export MATTERMOST_INCOME_URL=https://localhost:8065/hooks/3eo1wjwyxibnmd5rsusk4h4pgh    # your mattermost income url
# MATTERMOST_TOKEN: your mattermost token for **each Channel** --> comma seperated
export MATTERMOST_TOKEN="epboqd78ufyi58nxktgzq9zpho,7ftco7zg5fdkixw7j3okmuo3eo"
export HUBOT_HEROKU_KEEPALIVE_URL=http://127.0.0.1:8800/   # without this hubot won't start with default installation
export HUBOT_LOG_LEVEL=debug
#export MATTERMOST_CHANNEL=town-square # optional: if you want to override your channel
```

Also I did change the port of hubot with `export PORT=8000        # must be over 1000`, where the _PORT_ should be renamed to something like _HUBOT_PORT_, but this has nothing to do with _hubot-mattermost_.

Yes I thought that we would need a hubot per team. But then you need edited variables or another user context.

I think you can update the README.md with a remark that **MATTERMOST_CHANNEL** has to be unset/deleted. And perhaps another hint, that _working with more than 1 team requires a hubot instance per team_.

Thanks again for your effort and work. Nice!

**Comment by heitorlessa** [comment]
I'm glad it worked out well for you ;)

In terms of docs, we actually refer to that at the very beginning: [Environment Variables explanation](https://github.com/renanvicente/hubot-mattermost#environment-variables)

Instead of making a lot of changes in the doc for Hints, why not creating a Docker Container for Hubot-mattermost?

That would allow one container per Hubot + self-contained environment so one wouldn't necessarily need to reinvent the wheel and create multiple variables names (HUBOT1, HUBOT2) or work with chroot.

Maybe a new Issue for Hubot Docker option? I'm quite sure someone would be up to contribute on that -- Up to the challenge?

Tks again for the collaboration, much appreciated - I'm resolving this issue now

**Comment by jbick** [comment]
Another issue with listening to triggerwords and channels: Messages might be duplicated. E.g. listen to word "x" and listen to channel "a". If "x" is sent to channel "a" hubot will reply twice.

**Comment by devTechi** [comment]
Yes. There it is.

Great idea with docker. That would help a lot.

**Comment by thebeline** [comment]
@jbick - Is there a workaround for the duplication issue?  This is getting annoying (and dangerous).

I have hubot handling `giphy`, and this is posting multiple gifs to channels that are forwarding all traffic.  Perhaps just don't forward all traffic...  yes, but it would be swell if it didn't behave this way...  :-(

**Comment by jbick** [comment]
@thebeline Sorry for my late reply. We've stopped listening to channels because it was basically only fun stuff. A possible solution would be to run 2 different hubots. One listens to channels and the other listens to triggerswords. The one listening to channels should be modified to ignore everything with a triggerword. A better solution would be to modify mattermost.
